apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloapp-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: helloapp.126cb9aa92194a978a85.southcentralus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: helloapp-service
          servicePort: 80
        path: /
