apiVersion: v1
kind: Service
metadata:
  name: helloappstaging-service 
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP	
    targetPort: 8000
  selector:
    app: hello-appstaging
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloappstaging-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: hellostaging.24798a77325c49f9a4b6.eastus2.aksapp.io
    http:
      paths:
      - backend:
          serviceName: helloappstaging-service
          servicePort: 80
        path: /
