on:
  push:
    branches:
    - master
name: Build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout github code
      uses: actions/checkout@master
    
    - name: Build, Tag, and push container image to packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}
        registry: docker.pkg.github.com
        repository: robertefreeman/hello-demo/hellodemo
        tags: ${{ github.sha }} 
        tag_with_ref: true
  
  staging:
      needs: build
      name: deploy app to staging
      environment:
        name: staging
      runs-on: ubuntu-latest
      steps:
        
      - name: Checkout github code
        uses: actions/checkout@master
        
      - name: login to AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CRED }}' # Azure credentials
          resource-group: demoAks
          cluster-name: demoAks1
 
      - name: Set K8s secret for pulling container image
        uses: azure/k8s-create-secret@v1
        with:
          namespace: 'default'
          container-registry-url: ' docker.pkg.github.com'
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUBTOKEN }}
          secret-name: 'demo-k8s-secret'
        id: create-secret
        
      - name: azure deploy staging
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deploystage.yml
            manifests/service2.yml
          images: |
            docker.pkg.github.com/robertefreeman/hello-demo/hellodemo:${{ github.sha }} 
          imagepullsecrets: |
            demo-k8s-secret

  prod:
      needs: staging
      name: deploy app to prod
      environment:
        name: prod
      runs-on: ubuntu-latest
      steps:

      - name: Checkout github code
        uses: actions/checkout@master
        
      - name: login to AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CRED }}' # Azure credentials
          resource-group: demoAks
          cluster-name: demoAks1
 
      - name: Set K8s secret for pulling container image
        uses: azure/k8s-create-secret@v1
        with:
          namespace: 'default'
          container-registry-url: ' docker.pkg.github.com'
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUBTOKEN }}
          secret-name: 'demo-k8s-secret'
        id: create-secret
        
      - name: azure deploy prod
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
            manifests/prodservice.yml
          images: |
            docker.pkg.github.com/robertefreeman/hello-demo/hellodemo:${{ github.sha }} 
          imagepullsecrets: |
            demo-k8s-secret
