on:
  push:
    branches:
    - master
name: Build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}
        registry: docker.pkg.github.com
        repository: robertefreeman/hello-demo/hellodemo
        tags: latest, ${{ github.run_number }}
        tag_with_ref: true
    
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CRED }}' # Azure credentials
        resource-group: girhub-demos
        cluster-name: r0bk8s
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          docker.pkg.github.com/robertefreeman/hello-demo/hellodemo
