on:
  push:
    branches:
    - master
name: Build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: robertfreeman/hellodemo
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CRED }}' # Azure credentials
        resource-group: girhub-demos
        cluster-name: r0bk8s
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          docker.io/robertfreeman/hellodemo
